/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainMenu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author richard
 */
public class main extends javax.swing.JFrame {
    public main(String username) {
        setTitle("Dashboard");
        setSize(300, 150);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);

        JLabel welcomeLabel = new JLabel("Selamat datang, " + username + "!");
        welcomeLabel.setBounds(50, 50, 200, 30);
        add(welcomeLabel);
    }

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menus = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        navbar.setBackground(new java.awt.Color(0, 102, 0));
        navbar.setPreferredSize(new java.awt.Dimension(1016, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/naav(new).png"))); // NOI18N

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(0, 102, 0));
        sidebar.setPreferredSize(new java.awt.Dimension(250, 527));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        menus.setBackground(new java.awt.Color(0, 102, 0));
        menus.setForeground(new java.awt.Color(255, 255, 255));
        menus.setLayout(new javax.swing.BoxLayout(menus, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(menus);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1032, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pn_utama.add(new menu_bg());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menus;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/img/user.png"));
        ImageIcon iconDatker = new ImageIcon(getClass().getResource("/img/datker.png"));
        ImageIcon iconDash = new ImageIcon(getClass().getResource("/img/dash.png"));
        ImageIcon iconKriteria = new ImageIcon(getClass().getResource("/img/kriteria.png"));
        ImageIcon iconSkala = new ImageIcon(getClass().getResource("/img/skala.png"));
        ImageIcon iconReport = new ImageIcon(getClass().getResource("/img/report.png"));
        ImageIcon iconCreate = new ImageIcon(getClass().getResource("/img/create.png"));
        ImageIcon iconRead = new ImageIcon(getClass().getResource("/img/read.png"));
        ImageIcon iconDelete = new ImageIcon(getClass().getResource("/img/delete.png"));
        ImageIcon iconHitung = new ImageIcon(getClass().getResource("/img/perhitungan.png"));
        
        sidebar tambahDataKerugian = new sidebar(null, true, iconRead, "Tambah Data", null);
        
        sidebar menu = new sidebar(iconDash, false, null, "Menu", new ActionListener() {
            @Override 
            public void actionPerformed(ActionEvent e){
                pn_utama.removeAll();
                pn_utama.add(new menu_bg());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        sidebar tambahDataProduk = new sidebar(null, true, iconRead, "Tambah Data", new ActionListener() {
            @Override 
            public void actionPerformed(ActionEvent e){
                pn_utama.removeAll();
                pn_utama.add(new tambahDataProduk());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        sidebar editProduk = new sidebar(null, true, iconCreate, "Ubah Data", new ActionListener() {
            @Override 
            public void actionPerformed(ActionEvent e){
                pn_utama.removeAll();
                pn_utama.add(new crud_dataProduk());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        sidebar hitungAlternatif = new sidebar(iconDatker, false, null, "Alternatif", new ActionListener() {
            @Override 
            public void actionPerformed(ActionEvent e){
                pn_utama.removeAll();
                pn_utama.add(new alternatif());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        sidebar alternatif = new sidebar(iconKriteria, false, null, "Data Produk", null, tambahDataProduk, editProduk);
        sidebar hitungKriteria = new sidebar(iconHitung, false, null, "Matriks Kriteria", new ActionListener() {
            @Override 
            public void actionPerformed(ActionEvent e){
                pn_utama.removeAll();
                pn_utama.add(new kriteria());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        sidebar penilaian = new sidebar(iconSkala, false, null, "Penilaian", new ActionListener() {
            @Override 
            public void actionPerformed(ActionEvent e){
                pn_utama.removeAll();
                pn_utama.add(new penilaianProduk());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });

        sidebar Report = new sidebar(iconReport, false, null, "Report", new ActionListener() {
            @Override 
            public void actionPerformed(ActionEvent e){
                pn_utama.removeAll();
                pn_utama.add(new report());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        addMenu(menu, alternatif, penilaian,  hitungKriteria, hitungAlternatif, Report);
    }
    
    private void addMenu(sidebar... menu){
        for (int i = 0; i < menu.length; i++){
            menus.add(menu[i]);
            ArrayList<sidebar> submenu = menu[i].getSubmenu();
            for (sidebar m : submenu){
                addMenu(m);
            }
        }
        menus.revalidate();
    }
}
