/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mainMenu;

/**
 *
 * @author richard
 */
public class menu_bg extends javax.swing.JPanel {

    /**
     * Creates new form menu_bg
     */
    public menu_bg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCustom1 = new custom.panelCustom();
        abtname = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        abtket = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        abtobj = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom1.setRoundBottomLeft(50);
        panelCustom1.setRoundBottomRight(50);
        panelCustom1.setRoundTopLeft(50);
        panelCustom1.setRoundTopRight(50);
        panelCustom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        abtname.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        abtname.setForeground(new java.awt.Color(0, 102, 0));
        abtname.setText("Copyright @ Richard Eduardo P");
        panelCustom1.add(abtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tujulangit logo.png"))); // NOI18N
        panelCustom1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 6, -1, -1));

        abtket.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        abtket.setForeground(new java.awt.Color(0, 102, 0));
        abtket.setText("Tugas Akhir 2025");
        panelCustom1.add(abtket, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/labeltj.png"))); // NOI18N
        panelCustom1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 117, -1, -1));

        abtobj.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        abtobj.setForeground(new java.awt.Color(0, 102, 0));
        abtobj.setText("Tujulangit ForestPark");
        panelCustom1.add(abtobj, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.png"))); // NOI18N
        panelCustom1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 150, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg1.png"))); // NOI18N
        panelCustom1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 150, -1, -1));

        jPanel1.add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3020, 1610));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abtket;
    private javax.swing.JLabel abtname;
    private javax.swing.JLabel abtobj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private custom.panelCustom panelCustom1;
    // End of variables declaration//GEN-END:variables
}
