/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mainMenu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.HashMap;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author richard
 */
public class report extends javax.swing.JPanel {

    /**
     * Creates new form data_kerugian
     */
    public report() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        report = new javax.swing.JPanel();
        panelCustom1 = new custom.panelCustom();
        btn_preview = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jp = new javax.swing.JScrollPane();
        cb_report = new javax.swing.JComboBox<>();
        btn_print = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        main_panel.setLayout(new java.awt.CardLayout());

        report.setBackground(new java.awt.Color(0, 102, 0));
        report.setForeground(new java.awt.Color(204, 204, 204));

        panelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom1.setRoundBottomLeft(50);
        panelCustom1.setRoundBottomRight(50);
        panelCustom1.setRoundTopLeft(50);
        panelCustom1.setRoundTopRight(50);

        btn_preview.setBackground(new java.awt.Color(0, 102, 0));
        btn_preview.setForeground(new java.awt.Color(255, 255, 255));
        btn_preview.setText("Preview");
        btn_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previewActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("REPORT");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );

        cb_report.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cb_report.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Data", "Data Produk", "Data Penilaian Produk", "Data Kriteria", "Data Perankingan", " " }));
        cb_report.setToolTipText("");

        btn_print.setBackground(new java.awt.Color(0, 102, 0));
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCustom1Layout = new javax.swing.GroupLayout(panelCustom1);
        panelCustom1.setLayout(panelCustom1Layout);
        panelCustom1Layout.setHorizontalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom1Layout.createSequentialGroup()
                        .addGroup(panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCustom1Layout.createSequentialGroup()
                                .addComponent(cb_report, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCustom1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)))
                        .addGap(0, 657, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCustom1Layout.setVerticalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_report, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout reportLayout = new javax.swing.GroupLayout(report);
        report.setLayout(reportLayout);
        reportLayout.setHorizontalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        reportLayout.setVerticalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_panel.add(report, "card2");

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previewActionPerformed
        // TODO add your handling code here:
         Integer cb = cb_report.getSelectedIndex();
        JasperReport report;
          String jdbc_driver = "com.mysql.jdbc.Driver";
          String user = "root";
          String pass = "";
          String url = "jdbc:mysql://localhost:3306/db_tugasakhir";   
                File reportFile = new File(".");
         String dirr = "";
         
         if (cb == 1) {
    try {
        Class.forName(jdbc_driver);
        Connection cone = DriverManager.getConnection(url, user, pass);
        Statement stat = cone.createStatement();
        String sql = "SELECT " +
            "     tb_dataproduk.`idProduk` AS tb_dataproduk_idProduk, " +
            "     tb_dataproduk.`namaProduk` AS tb_dataproduk_namaProduk " +
            "FROM " +
            "     `tb_dataproduk` tb_dataproduk";
        dirr = reportFile.getCanonicalPath() + "/src/report/";

        JasperDesign design = JRXmlLoader.load(dirr + "dataProduk.jrxml");
        JasperReport jr = JasperCompileManager.compileReport(design);
        ResultSet rs = stat.executeQuery(sql);
        JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
        
        JasperPrint jasperPrint = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);
        JRViewer viewer = new JRViewer(jasperPrint);

        jp.setViewportView(viewer);  // ← tampilkan viewer ke JScrollPane

    } catch (Exception ex) {
        Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }  
}

         if (cb == 2) {
            try {
                Class.forName(jdbc_driver);
                Connection cone = DriverManager.getConnection(url, user, pass);
                Statement stat = cone.createStatement();
                String sql = "SELECT " +
                    "     tb_dataproduk.`idProduk` AS tb_dataproduk_idProduk, " +
                    "     tb_dataproduk.`namaProduk` AS tb_dataproduk_namaProduk, " +
                    "     tb_dataproduk.`kualitas` AS tb_dataproduk_kualitas, " +
                    "     tb_dataproduk.`penjualan` AS tb_dataproduk_penjualan, " +
                    "     tb_dataproduk.`stok` AS tb_dataproduk_stok, " +
                    "     tb_dataproduk.`rating` AS tb_dataproduk_rating " +
                    "FROM " +
                    "     `tb_dataproduk` tb_dataproduk";
                dirr = reportFile.getCanonicalPath() + "/src/report/";

                JasperDesign design = JRXmlLoader.load(dirr + "penilaianProduk.jrxml");
                JasperReport jr = JasperCompileManager.compileReport(design);
                ResultSet rs = stat.executeQuery(sql);
                JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);

                JasperPrint jasperPrint = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);
                JRViewer viewer = new JRViewer(jasperPrint);

                jp.setViewportView(viewer);  // ← tampilkan viewer ke JScrollPane

            } catch (Exception ex) {
                Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }
        }
         
         if (cb == 3) {
            try {
                Class.forName(jdbc_driver);
                Connection cone = DriverManager.getConnection(url, user, pass);
                Statement stat = cone.createStatement();
                String sql = "SELECT " +
                    "     tb_kriteria.`idKriteria` AS tb_kriteria_idKriteria, " +
                    "     tb_kriteria.`namaKriteria` AS tb_kriteria_namaKriteria, " +
                    "     tb_kriteria.`bobotKriteria` AS tb_kriteria_bobotKriteria " +
                    "FROM " +
                    "     `tb_kriteria` tb_kriteria";
                dirr = reportFile.getCanonicalPath() + "/src/report/";

                JasperDesign design = JRXmlLoader.load(dirr + "kriteria.jrxml");
                JasperReport jr = JasperCompileManager.compileReport(design);
                ResultSet rs = stat.executeQuery(sql);
                JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);

                JasperPrint jasperPrint = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);
                JRViewer viewer = new JRViewer(jasperPrint);

                jp.setViewportView(viewer);  // ← tampilkan viewer ke JScrollPane

            } catch (Exception ex) {
                Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }
        }
         
         if (cb == 4) {
            try {
                Class.forName(jdbc_driver);
                Connection cone = DriverManager.getConnection(url, user, pass);
                Statement stat = cone.createStatement();
                String sql = "SELECT " +
                    "     tb_ranking.`idRanking` AS tb_ranking_idRanking, " +
                    "     tb_ranking.`namaProduk` AS tb_ranking_namaProduk, " +
                    "     tb_ranking.`skorProduk` AS tb_ranking_skorProduk, " +
                    "     tb_ranking.`peringkatProduk` AS tb_ranking_peringkatProduk " +
                    "FROM " +
                    "     `tb_ranking` tb_ranking";
                dirr = reportFile.getCanonicalPath() + "/src/report/";

                JasperDesign design = JRXmlLoader.load(dirr + "perankingan.jrxml");
                JasperReport jr = JasperCompileManager.compileReport(design);
                ResultSet rs = stat.executeQuery(sql);
                JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);

                JasperPrint jasperPrint = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);
                JRViewer viewer = new JRViewer(jasperPrint);

                jp.setViewportView(viewer);  // ← tampilkan viewer ke JScrollPane

            } catch (Exception ex) {
                Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            }
        }

    }//GEN-LAST:event_btn_previewActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        Integer cb = cb_report.getSelectedIndex(); // pastikan cb_report dideklarasi
        String jdbc_driver = "com.mysql.cj.jdbc.Driver";
        String user = "root";
        String pass = "";
        String url = "jdbc:mysql://localhost:3306/db_tugasakhir";
        File reportFile = new File(".");
        String dirr = "";
        
        if (cb == 1) {
            try {
                // Tidak perlu lagi Class.forName(jdbc_driver) secara eksplisit
                try (Connection cone = DriverManager.getConnection(url, user, pass);
                     Statement stat = cone.createStatement()) {

                    String sql = "SELECT " +
                        "     tb_dataproduk.`idProduk` AS tb_dataproduk_idProduk, " +
                        "     tb_dataproduk.`namaProduk` AS tb_dataproduk_namaProduk " +
                        "FROM " +
                        "     `tb_dataproduk` tb_dataproduk";

                    // Gunakan Paths agar cross-platform
                    dirr = Paths.get(reportFile.getCanonicalPath(), "/src/report/").toString();

                    JasperDesign design = JRXmlLoader.load(new File(dirr, "dataProduk.jrxml"));
                    JasperReport jr = JasperCompileManager.compileReport(design);
                    ResultSet rs = stat.executeQuery(sql);
                    JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
                    JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);

                    JFrame frame = new JFrame("Report");
                    frame.getContentPane().add(new JRViewer(jp));
                    frame.pack();
                    frame.setVisible(true);
                }

            } catch (SQLException | IOException | JRException ex) {
                JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex,
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        }

        if (cb == 2) {
            try {
                // Tidak perlu lagi Class.forName(jdbc_driver) secara eksplisit
                try (Connection cone = DriverManager.getConnection(url, user, pass);
                     Statement stat = cone.createStatement()) {

                    String sql = "SELECT " +
                        "     tb_dataproduk.`idProduk` AS tb_dataproduk_idProduk, " +
                        "     tb_dataproduk.`namaProduk` AS tb_dataproduk_namaProduk, " +
                        "     tb_dataproduk.`kualitas` AS tb_dataproduk_kualitas, " +
                        "     tb_dataproduk.`penjualan` AS tb_dataproduk_penjualan, " +
                        "     tb_dataproduk.`stok` AS tb_dataproduk_stok, " +
                        "     tb_dataproduk.`rating` AS tb_dataproduk_rating " +
                        "FROM " +
                        "     `tb_dataproduk` tb_dataproduk";

                    // Gunakan Paths agar cross-platform
                    dirr = Paths.get(reportFile.getCanonicalPath(), "/src/report/").toString();

                    JasperDesign design = JRXmlLoader.load(new File(dirr, "penilaianProduk.jrxml"));
                    JasperReport jr = JasperCompileManager.compileReport(design);
                    ResultSet rs = stat.executeQuery(sql);
                    JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
                    JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);

                    JFrame frame = new JFrame("Report");
                    frame.getContentPane().add(new JRViewer(jp));
                    frame.pack();
                    frame.setVisible(true);
                }

            } catch (SQLException | IOException | JRException ex) {
                JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex,
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if (cb == 3) {
            try {
                // Tidak perlu lagi Class.forName(jdbc_driver) secara eksplisit
                try (Connection cone = DriverManager.getConnection(url, user, pass);
                     Statement stat = cone.createStatement()) {

                    String sql = "SELECT " +
                        "     tb_kriteria.`idKriteria` AS tb_kriteria_idKriteria, " +
                        "     tb_kriteria.`namaKriteria` AS tb_kriteria_namaKriteria, " +
                        "     tb_kriteria.`bobotKriteria` AS tb_kriteria_bobotKriteria " +
                        "FROM " +
                        "     `tb_kriteria` tb_kriteria";

                    // Gunakan Paths agar cross-platform
                    dirr = Paths.get(reportFile.getCanonicalPath(), "/src/report/").toString();

                    JasperDesign design = JRXmlLoader.load(new File(dirr, "kriteria.jrxml"));
                    JasperReport jr = JasperCompileManager.compileReport(design);
                    ResultSet rs = stat.executeQuery(sql);
                    JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
                    JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);

                    JFrame frame = new JFrame("Report");
                    frame.getContentPane().add(new JRViewer(jp));
                    frame.pack();
                    frame.setVisible(true);
                }

            } catch (SQLException | IOException | JRException ex) {
                JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex,
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if (cb == 4) {
            try {
                // Tidak perlu lagi Class.forName(jdbc_driver) secara eksplisit
                try (Connection cone = DriverManager.getConnection(url, user, pass);
                     Statement stat = cone.createStatement()) {

                    String sql = "SELECT " +
                        "     tb_ranking.`idRanking` AS tb_ranking_idRanking, " +
                        "     tb_ranking.`namaProduk` AS tb_ranking_namaProduk, " +
                        "     tb_ranking.`skorProduk` AS tb_ranking_skorProduk, " +
                        "     tb_ranking.`peringkatProduk` AS tb_ranking_peringkatProduk " +
                        "FROM " +
                        "     `tb_ranking` tb_ranking";

                    // Gunakan Paths agar cross-platform
                    dirr = Paths.get(reportFile.getCanonicalPath(), "/src/report/").toString();

                    JasperDesign design = JRXmlLoader.load(new File(dirr, "perankingan.jrxml"));
                    JasperReport jr = JasperCompileManager.compileReport(design);
                    ResultSet rs = stat.executeQuery(sql);
                    JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
                    JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap<>(), rsDataSource);

                    JFrame frame = new JFrame("Report");
                    frame.getContentPane().add(new JRViewer(jp));
                    frame.pack();
                    frame.setVisible(true);
                }

            } catch (SQLException | IOException | JRException ex) {
                JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex,
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btn_printActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_preview;
    private javax.swing.JButton btn_print;
    private javax.swing.JComboBox<String> cb_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jp;
    private javax.swing.JPanel main_panel;
    private custom.panelCustom panelCustom1;
    private javax.swing.JPanel report;
    // End of variables declaration//GEN-END:variables
}
